name: Build and release on PyPi

on:
  push:
    tags:
      - v*

concurrency:
  group: build-dendromatics-${{ github.head_ref }}

jobs:
  build:
    name: Build dendromatics source package and wheel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Hatch
        run: python -m pip install --upgrade hatch

      - name: Build artifacts
        run: hatch build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
